### PR TITLE
Feature/v3

### PR DESCRIPTION
**Pull request by eluhr**
As the new usuario version now support anything we do in this package is not really needed anymore. But instead of removing it i would suggest we transform it in some sort of a guide on how to use keycloak as an auth provider in yii2 with some optional files and classes.

### CODE REVIEW

**Comment by eluhr** [comment]
@schmunk42 Added `findIdentityByAccessToken` example in readme

**Comment by eluhr** [comment]
I also added a example init.sql dump with a preconfigured example realm and client.

**Review by schmunk42 — COMMENTED** [review]
LGTM from what I can tell :)

**Review by amk0 — APPROVED** [review]

**Review by amk0 — APPROVED** [review]
Looks good.
Only thing would be to check with 2amigos about "2amigos/yii2-usuario": "^1.6.2" version

**Comment by eluhr** [comment]
For this to work, we need features that are not yet included in a stable [usuario](https://github.com/2amigos/yii2-usuario) release.

@maxxer: When are you planning to release a new version for usuario? Specifically, this involves the following (merged) changes:

- https://github.com/2amigos/yii2-usuario/pull/537
- https://github.com/2amigos/yii2-usuario/pull/535
- https://github.com/2amigos/yii2-usuario/pull/544

**Comment by maxxer** [comment]
I can tag a release later this week

**Comment by eluhr** [comment]
@maxxer is a release planned for this week?

**Comment by maxxer** [comment]
Tagged 1.6.3 now!

**Pull request merged**
